<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <!-- Versión global de Spring Boot para microservicios -->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.4</version> 
        <relativePath/>
    </parent>

    <groupId>com.example</groupId>
    <artifactId>ecommerce-parent</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging> <!-- IMPORTANTÍSIMO: Indica que es un contenedor, no una app ejecutable -->

    <!-- Aquí dentro meterás las carpetas de tus microservicios -->
    <modules>
        <!-- <module>customer-service</module>
        <module>order-service</module> -->
        <module>auth-service</module>
        <module>stock-service</module>
    </modules>

    <properties>
        <java.version>21</java.version>
    </properties>
</project>
