spring:
  application:
    name: stock-service
 
  mongodb:
    uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@localhost:27018/stock_db?authSource=admin
 
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
 
server:
  port: ${SERVER_PORT:8082}
 
app:
  kafka:
    topic:
      order-created: order-created
    consumer-group: stock-service-group
 
logging:
  level:
    stock_service: DEBUG